### ISSUE TITLE
Saving self-calibration models.

### ISSUE THREAD

**Issue by YasuThompson** [TRI-ML/vidar#17]
Hi. 
I have several questions about saving models to a local folder. 

1, When I run the self-calibration code, when are trained models saved to?
2, Which part of config files should I 
3, Could you point to the part of the code which saves trained models?

I am sorry for the effortless basic questions. 
But I am now confused how config files are processed.

**Comment by KOuldamer** [comment]
Hi, 
Where i can find the infernce script of self-calibration method ?

**Comment by YasuThompson** [comment]
I actually found that I had only to add the following to at the bottom of for example `ucm_euroc.yaml` to enable saving models. 

```
checkpoint:
    folder: /data/vidar/checkpoints       # Local folder to store checkpoints
    save_code: True                       # Save repository folder as well
    keep_top: 5                           # How many checkpoints should be stored
```

And trained models are saved in directories like `2022-08-02_06h02m10s/models/001.ckpt` 
But I want to know how I can visualize depth maps with the trained models.
